[package]
edition = "2021"
name = "autocxx-crash"
version = "0.0.0"

[build-dependencies]
autocxx-build = "0.25"
cxx-build = "1.0"
miette = { version = "5.5", features = ["fancy"] }

[dependencies]
autocxx = "0.25"
cxx = "1.0"
